version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigdata
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data